"""Adding storage table.

Revision ID: 9397cb79870d
Revises: 9bebe894199c
Create Date: 2025-07-31 17:03:51.127215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9397cb79870d'
down_revision: Union[str, Sequence[str], None] = '9bebe894199c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###    
    op.create_table('storage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('storage_id', sa.Integer(), nullable=True),
    sa.Column('storage_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['property.location.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['property.rooms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='property'
    )
    op.create_index(op.f('ix_property_storage_id'), 'storage', ['id'], unique=False, schema='property')
    op.create_index(op.f('ix_property_storage_storage_name'), 'storage', ['storage_name'], unique=False, schema='property')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_property_storage_storage_name'), table_name='storage', schema='property')
    op.drop_index(op.f('ix_property_storage_id'), table_name='storage', schema='property')
    op.drop_table('storage', schema='property')    
    # ### end Alembic commands ###
