"""Adding LocationPath table.

Revision ID: e4eb2bfef818
Revises: a2e52a662590
Create Date: 2025-08-10 11:41:18.013838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4eb2bfef818'
down_revision: Union[str, Sequence[str], None] = 'a2e52a662590'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_path',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('storage_id', sa.Integer(), nullable=False),
    sa.Column('location_path', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['property.location.id'], ),
    sa.ForeignKeyConstraint(['storage_id'], ['property.storage.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='property'
    )
    op.create_index(op.f('ix_property_location_path_id'), 'location_path', ['id'], unique=False, schema='property')
    op.create_index(op.f('ix_property_location_path_location_path'), 'location_path', ['location_path'], unique=False, schema='property')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_property_location_path_location_path'), table_name='location_path', schema='property')
    op.drop_index(op.f('ix_property_location_path_id'), table_name='location_path', schema='property')
    op.drop_table('location_path', schema='property')
    # ### end Alembic commands ###
