"""Removing family table.

Revision ID: 466366336567
Revises: deaedb131bd6
Create Date: 2025-07-24 19:33:45.354199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '466366336567'
down_revision: Union[str, Sequence[str], None] = 'deaedb131bd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_family_id'), table_name='family')
    op.drop_table('family')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('family',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('family_uuid', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_added', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('family_pkey'))
    )
    op.create_index(op.f('ix_family_id'), 'family', ['id'], unique=False)
    # ### end Alembic commands ###
