"""Deleting older revisions and adding schema user to tables. Removing association module from user_service module.

Revision ID: c5a5c59675ed
Revises: 
Create Date: 2025-07-31 16:45:00.362825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5a5c59675ed'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.LargeBinary(), nullable=False),
    sa.Column('salt', sa.LargeBinary(), nullable=False),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='user'
    )
    op.create_index(op.f('ix_user_details_id'), 'details', ['id'], unique=False, schema='user')
    op.create_table('passwords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_str', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.details.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='user'
    )
    op.create_index(op.f('ix_user_passwords_id'), 'passwords', ['id'], unique=False, schema='user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_passwords_id'), table_name='passwords', schema='user')
    op.drop_table('passwords', schema='user')
    op.drop_index(op.f('ix_user_details_id'), table_name='details', schema='user')
    op.drop_table('details', schema='user')
    # ### end Alembic commands ###
