[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
name = "j4s_logging_lib"
version = "0.1.0"
description = "Reusable logging module for services"
dependencies = []

[tool.setuptools.packages.find]
where = ["."]