"""Adding search_vector of type TSVECTOR and gin index

Revision ID: 43c17cdf145e
Revises: 28b53d238f50
Create Date: 2025-08-10 21:19:55.007075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '43c17cdf145e'
down_revision: Union[str, Sequence[str], None] = '28b53d238f50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True), schema='household')
    op.create_index('ix_household_search_idx', 'items', ['search_vector'], unique=False, schema='household', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_household_search_idx', table_name='items', schema='household', postgresql_using='gin')
    op.drop_column('items', 'search_vector', schema='household')
    # ### end Alembic commands ###
