"""Inventory Household database.

Revision ID: 61d4ff714350
Revises: 9c2f9bf91003
Create Date: 2025-08-10 14:07:47.676194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61d4ff714350'
down_revision: Union[str, Sequence[str], None] = '9c2f9bf91003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('household',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('general_name', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('storage_id', sa.Integer(), nullable=True),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='inventory'
    )
    op.create_index(op.f('ix_inventory_household_general_name'), 'household', ['general_name'], unique=False, schema='inventory')
    op.create_index(op.f('ix_inventory_household_id'), 'household', ['id'], unique=False, schema='inventory')
    op.create_index(op.f('ix_inventory_household_product_name'), 'household', ['product_name'], unique=False, schema='inventory')
    op.create_index(op.f('ix_inventory_household_property_id'), 'household', ['property_id'], unique=False, schema='inventory')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_household_property_id'), table_name='household', schema='inventory')
    op.drop_index(op.f('ix_inventory_household_product_name'), table_name='household', schema='inventory')
    op.drop_index(op.f('ix_inventory_household_id'), table_name='household', schema='inventory')
    op.drop_index(op.f('ix_inventory_household_general_name'), table_name='household', schema='inventory')
    op.drop_table('household', schema='inventory')
    # ### end Alembic commands ###
